name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[d1_databases]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"
database_id = "b550249a-ec49-40e0-949d-4432d480e23b"
